creating a map including geojson data
MackyDIARRA/electricitymap_dashboard pull request #2
Opened 2022-01-28 14:13 UTC by MackyDIARRA

I had to import the zones.json file which allows me to retrieve the coordinates of each country mentioned on the map but I cannot manage to create the interface which makes it possible to concretely open the plotted data corresponding to each country

2022-01-28 15:02 UTC, martinRenou commented on Untitled.ipynb
> +    "find = str(input(\"veuillez rentrer le code du pays correspondant : \"))\n",
For now you're using `input`, but you should probably remove that and to this programmatically when clicking on the map

2022-01-28 15:02 UTC, martinRenou commented on Untitled.ipynb
> +    "fig\n",
Suggestion: Make this part a function that you can reuse later

2022-01-28 15:02 UTC, martinRenou commented on Untitled.ipynb
> +    "\n",
I guess you're missing the part that creates the plot when clicking on the map now :)

I'd suggest to look at using this method: https://github.com/jupyter-widgets/ipyleaflet/blob/master/ipyleaflet/leaflet.py#L1243

2022-01-28 15:05 UTC, martinRenou commented on Untitled.ipynb
> +    "\n",
There is a similar dashboard to what you are trying to achieve here: https://github.com/jupyter-widgets/ipyleaflet/blob/master/examples/WealthOfNations.ipynb

The only difference is that they are using `on_hover` and not `on_click`

2022-02-01 10:05 UTC, martinRenou commented on Trees.ipynb
> +{
This might have been committed by mistake?

2022-02-01 10:05 UTC, MackyDIARRA commented
I have been renamed my "untitled.ipynb" notebook to "Electricity_map.ipynb". I tried to adapt https://github.com/jupyter-widgets/ipyleaflet/blob/master/examples/WealthOfNations.ipynb notebook in my notebook but I can't find a solution that allows me to display the plot of each country when I click on a country on the map

2022-02-01 10:06 UTC, MackyDIARRA commented on Trees.ipynb
> +{
no I've submitted my progress

2022-02-01 10:07 UTC, MackyDIARRA commented on Trees.ipynb
> +{
aah yes for this notebook

2022-02-01 10:25 UTC, martinRenou requested changes

2022-02-01 10:25 UTC, martinRenou commented on Electricity_map.ipynb
> +    "    if country == \"click\" :\n",
The country variable is not defined?

2022-02-01 10:25 UTC, martinRenou commented on Electricity_map.ipynb
> +    "def mapping(param1) :\n",
Your function creates a bar chart, "mapping" does not seem like a proper name for it?

2022-02-01 10:29 UTC, MackyDIARRA commented on Electricity_map.ipynb
> +    "    if country == \"click\" :\n",
sorry I wanted to put type not "country"

2022-02-01 10:33 UTC, MackyDIARRA commented on Electricity_map.ipynb
> +    "def mapping(param1) :\n",
It was supposed to be a test but I will modify it

2022-02-01 10:37 UTC, martinRenou commented on Electricity_map.ipynb
> +    "    if country == \"click\" :\n",
`type` is also not defined, that might not be what you want to do. At this point in the code you already know that it's a click event, so this condition might not be needed :)

2022-02-01 10:42 UTC, MackyDIARRA commented on Electricity_map.ipynb
> +    "    if country == \"click\" :\n",
okay I just got it

2022-02-17 10:16 UTC, MackyDIARRA reviewed
I deleted every unnecessary files which I don't need

2022-02-17 10:22 UTC, martinRenou commented on Electricity_map.ipynb
> +    "Element = {'Map': app , 'Figure': fig}\n",
The 'Map' pane you are defining here uses the `app` variable which contains the bqplot figure `fig`, so you are using the figure twice in the flex layout?

2022-02-17 10:27 UTC, MackyDIARRA reviewed
I created a new notebook that can contribute for the making of my dashboard in my notebook Electricity_map.ipynb

2022-02-17 10:31 UTC, martinRenou commented on Electricity_map.ipynb
> +    "    data2 = fetch_price()\n",
This makes the callback fail on my side. You are not using the `data2` variable, so I would remove this line for now.

2022-02-17 10:32 UTC, MackyDIARRA commented on Electricity_map.ipynb
> +    "    data2 = fetch_price()\n",
sorry I will delete it too

2022-02-17 10:38 UTC, MackyDIARRA reviewed
I deleted a  data2 and price data variable

2022-02-17 10:39 UTC, merged

2022-02-17 10:41 UTC, martinRenou commented
There is another occurrence of `data2` in your Notebook that you might have missed? The one pointed by my comment above